package:
  name: PIED
  version: "0.0.11"

source:
  git_url: https://github.com/isaacovercast/PIED
  git_tag: master

build:
  number: 11
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - msprime
    - cython
    - numpy
    - pandas
  run:
    - python >=3
    - setuptools
    - ipyparallel
    - cython
    - scipy
    - nbconvert
    - joblib
    - jupyter
    - pandas
    - matplotlib
    - momi
    - msprime
    - cloudpickle

  commands:
    - PIED -v

about:
  home: https://github.com/isaacovercast/PIED
  license: GPLv3
  summary: PIED
