package:
  name: pied
  version: "0.0.11"

source:
  git_url: https://github.com/isaacovercast/PIED
  git_tag: master

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3
    - setuptools
    - msprime
    - numpy
    - pandas
  run:
    - python >=3
    - setuptools
    - ipyparallel
    - pandas
    - matplotlib
    - msprime
    - cloudpickle
    - toytree

  commands:
    - PIED -v

about:
  home: https://github.com/isaacovercast/PIED
  license: GPLv3
  summary: PIED
