package:
  name: ibiogen
  version: "0.0.8"

source:
  git_url: https://github.com/iBioGen/iBioGen
  git_tag: master

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3
    - setuptools
    - msprime
    - numpy
    - pandas
  run:
    - python >=3
    - setuptools
    - ipyparallel
    - pandas
    - matplotlib
    - msprime
    - cloudpickle
    - toytree
    - scipy

  commands:
    - iBioGen -v

about:
  home: https://github.com/iBioGen/iBioGen
  license: GPLv3
  summary: iBioGen
